/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutPlaylistRouteImport } from './routes/_layout/playlist'
import { Route as LayoutAlbumIdRouteImport } from './routes/_layout/$albumId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaylistRoute = LayoutPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlbumIdRoute = LayoutAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/$albumId': typeof LayoutAlbumIdRoute
  '/playlist': typeof LayoutPlaylistRoute
}
export interface FileRoutesByTo {
  '/$albumId': typeof LayoutAlbumIdRoute
  '/playlist': typeof LayoutPlaylistRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$albumId': typeof LayoutAlbumIdRoute
  '/_layout/playlist': typeof LayoutPlaylistRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$albumId' | '/playlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/$albumId' | '/playlist' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$albumId'
    | '/_layout/playlist'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playlist': {
      id: '/_layout/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof LayoutPlaylistRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$albumId': {
      id: '/_layout/$albumId'
      path: '/$albumId'
      fullPath: '/$albumId'
      preLoaderRoute: typeof LayoutAlbumIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAlbumIdRoute: typeof LayoutAlbumIdRoute
  LayoutPlaylistRoute: typeof LayoutPlaylistRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAlbumIdRoute: LayoutAlbumIdRoute,
  LayoutPlaylistRoute: LayoutPlaylistRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
