/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlbumRouteImport } from './routes/_album'
import { Route as AlbumIndexRouteImport } from './routes/_album/index'
import { Route as AlbumAlbumIdRouteImport } from './routes/_album/$albumId'

const AlbumRoute = AlbumRouteImport.update({
  id: '/_album',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIndexRoute = AlbumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumRoute,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AlbumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AlbumIndexRoute
  '/$albumId': typeof AlbumAlbumIdRoute
}
export interface FileRoutesByTo {
  '/$albumId': typeof AlbumAlbumIdRoute
  '/': typeof AlbumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_album': typeof AlbumRouteWithChildren
  '/_album/$albumId': typeof AlbumAlbumIdRoute
  '/_album/': typeof AlbumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to: '/$albumId' | '/'
  id: '__root__' | '/_album' | '/_album/$albumId' | '/_album/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AlbumRoute: typeof AlbumRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_album': {
      id: '/_album'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_album/': {
      id: '/_album/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AlbumIndexRouteImport
      parentRoute: typeof AlbumRoute
    }
    '/_album/$albumId': {
      id: '/_album/$albumId'
      path: '/$albumId'
      fullPath: '/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof AlbumRoute
    }
  }
}

interface AlbumRouteChildren {
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  AlbumIndexRoute: typeof AlbumIndexRoute
}

const AlbumRouteChildren: AlbumRouteChildren = {
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  AlbumIndexRoute: AlbumIndexRoute,
}

const AlbumRouteWithChildren = AlbumRoute._addFileChildren(AlbumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AlbumRoute: AlbumRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
